//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMOz.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMOz.Resources.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}
        ///
        ///SMOz uses the following components:
        ///     Magic Control Library 1.7.4.0:  Phil Wright &lt;http://www.dotnetmagic.com/&gt;
        ///     XPTable: Mathew Hall &lt;http://www.codeproject.com/cs/miscctrl/XPTable.asp&gt;
        ///     EXListView: Michiel van Eerd &lt;http://www.webessence.nl/&gt;
        ///     SysIconList: vbAccelerator &lt;http://vbaccelerator.com/&gt;
        ///
        ///The default template includes contributions from:
        ///     Matt Bentley &lt;soulstudios@orcon.net.nz&gt;
        ///     
        ///The author would like to thank the following users for their generous fin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutContributorsFormat {
            get {
                return ResourceManager.GetString("AboutContributorsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
        ///
        ///You should have received a copy  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}
        ///Written by Nithin Philips &lt;spikiermonkey@users.sourceforge.net&gt;.
        ///
        ///Copyright (C) 2004-2006 Nithin Philips.
        ///This is free software; There is NO warranty
        ///not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        ///
        ///Read COPYING in application directory or visit http://www.gnu.org/copyleft/gpl.html for more info..
        /// </summary>
        internal static string AboutVersionFormat {
            get {
                return ResourceManager.GetString("AboutVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        internal static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Template.
        /// </summary>
        internal static string ApplyTemplate {
            get {
                return ResourceManager.GetString("ApplyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        internal static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Items.
        /// </summary>
        internal static string DeleteItemsFormat {
            get {
                return ResourceManager.GetString("DeleteItemsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Name Is Not Valid.
        /// </summary>
        internal static string EnteredNameIsNotValid {
            get {
                return ResourceManager.GetString("EnteredNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} Items.
        /// </summary>
        internal static string MoveItemsFormat {
            get {
                return ResourceManager.GetString("MoveItemsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Selected.
        /// </summary>
        internal static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, But there is nothing to do!.
        /// </summary>
        internal static string NothingToDoMessage {
            get {
                return ResourceManager.GetString("NothingToDoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the operations ({0}) has failed. All Changes will be restored.
        ///
        ///Reason: {1}.
        /// </summary>
        internal static string OperationFailedMessageFormat {
            get {
                return ResourceManager.GetString("OperationFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed.
        /// </summary>
        internal static string Renamed {
            get {
                return ResourceManager.GetString("Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Search Results&gt;.
        /// </summary>
        internal static string SearchResultsNodeName {
            get {
                return ResourceManager.GetString("SearchResultsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some items in the start menu was modified by an another application. Applying changes made in SMOz may result in unpredictable state..
        /// </summary>
        internal static string StartMenuModifiedMessage {
            get {
                return ResourceManager.GetString("StartMenuModifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty).
        /// </summary>
        internal static string UnCategorizedNodeName {
            get {
                return ResourceManager.GetString("UnCategorizedNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you have unsaved changes. Do you still want to quit?.
        /// </summary>
        internal static string UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("UnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
